### ISSUE TITLE
Clean code

### ISSUE THREAD

**Issue by Archi657** [Sergio-a11/bici#2]
Como tenemos las ruta de registro de usuarios como register, pero igual tenemos register de bicicletas, cupos e.t.c, propongo utilizar 
/registerUser /registerBike /registerSlot etc....
para tenerlo organizado todas las operaciones de crud estilo
/registerUser /deleteUser /updateUser /getUser
/registerBike /deleteBike /updateBike /getBike
por lo cual a la ruta register falta añadirle registerUser o registerUsuarios y comenzar a escribir cada uno de dicha forma, y tambien diria que unifiquemos si vamos a escribir el codigo al fin en ingles o español.

**Comment by Sergio-a11** [comment]
Buena sugerencia, debemos usar nombres más declarativos, cambiar las rutas como dice @Archi657, yo diría que @DanndxFull se encargue de los usuarios  y @Archi657 de las bicicletas, y el código en español porque Peter se pega de eso,

@Archi657 revise la forma en que se están registrando los usuarios por medio de la aplicación, vea que desde la interfaz en vez de usar un Hashmap le estamos indicando que espere un usuario de forma que no nos da problemas por tener valores de distintos tipos de datos

**Comment by Sergio-a11** [comment]
> Como tenemos las ruta de registro de usuarios como register, pero igual tenemos register de bicicletas, cupos e.t.c, propongo utilizar 
> /registerUser /registerBike /registerSlot etc....
> para tenerlo organizado todas las operaciones de crud estilo
> /registerUser /deleteUser /updateUser /getUser
> /registerBike /deleteBike /updateBike /getBike
> por lo cual a la ruta register falta añadirle registerUser o registerUsuarios y comenzar a escribir cada uno de dicha forma, y tambien diria que unifiquemos si vamos a escribir el codigo al fin en ingles o español.
> 

Primero acabar un crud y de paso poner la estandarización que menciona

**Comment by DanndxFull** [comment]
Unificar los cruds de node para que se cree uno de cada accion de forma generalizada y funcional para el resto de cruds
