### ISSUE TITLE
Validar longitud de campos según la BD y campos con contenido desde Android para que no explote, puede ser en el botón que envía el form

### ISSUE THREAD

**Issue by Sergio-a11** [Sergio-a11/bici#7]
@Archi657

**Comment by Archi657** [comment]
![image](https://user-images.githubusercontent.com/40327956/181924553-1069423b-dcee-451d-8c4e-c5afa7cdd1e2.png)
Lineas comentadas : Codigo añadido.

Intente realizarlo con un if que verifique el tamaño y de una vez el tipo, pues el length solo funcionara con string, y la idea seria con los int mirar getClass() y verificar el tipo de dato.

pero al ejecutar el android ni abre la aplicación.  y no he podido probarlo, junto al codigo añadido de las IPs, se me rompio el android pero podrían verificar si funciona así. Intentare probar ese  código en otra rama de prueba.
